version: '3.0'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./data:/home/wpdata:rw
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wproot
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./uploads:/var/www/html/wp-content/uploads:rw
       - ./plugins/demo:/var/www/html/wp-content/plugins/demo
       - ./themes/demo:/var/www/html/wp-content/themes/demo
     ports:
       - 8000:80
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
   
   myadmin:
     image: "phpmyadmin/phpmyadmin"
     ports:
       - 8002:80
     links:
       - db:mysql
     environment:
       - PMA_HOST=mysql
       - PMA_USER=wordpress
       - PMA_PASSWORD=wordpress
       - PMA_ARBITRARY=1
volumes:
    dbdata:

